Class specified by `SENTRY_TSDB` does not exist
Corrects the Docker config value for `SENTRY_TSDB` to point to the correct class.

This resulted in errors for me:

```
│ !! Configuration error: ConfigurationError("sentry.tsdb service failed to call validate()\nmodule 'sentry.tsdb.redis' has no attribute 'RedisSnubaTSDB'")                                             ```

Note that this works in 22.9, but the above error occurs in 22.10